version: 2.1
dependencies:
  pre:
    - curl -s https://raw.githubusercontent.com/chronogolf/circleci-google-chrome/master/use_chrome_stable_version.sh | bash
orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@2.0.6
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build-deploy:
    docker:
      - image: "cimg/node:14.19.1-browsers"
    steps:
      - checkout
      - node/install:
          node-version: '14.19.1'
      - aws-cli/setup
      - eb/setup
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Angular CLI Dependencies
          command: |
            npm i -g @angular/cli 
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Front-End Test
          command: |
            npm run frontend:test
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Deploy
          command: |
            npm run backend:deploy
      - run:
          name: Front-End Deploy
          command: |
            npm run frontend:deploy
workflows:
  udagram:
    jobs:
      - build-deploy:
          filters:
            branches:
              only: /^master/